# Generated by Django 4.0.1 on 2022-01-08 17:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(default='1970-01-01')),
                ('photo', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mark', models.IntegerField()),
                ('rating', models.FloatField()),
                ('poster', models.ImageField(upload_to='')),
                ('trailer', models.CharField(max_length=255)),
                ('production_year', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_fan.director')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('date_registration', models.DateField(default=datetime.date(2022, 1, 8))),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date(2022, 1, 8))),
                ('likes_count', models.IntegerField()),
                ('dislikes_count', models.IntegerField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_fan.movie')),
            ],
        ),
    ]
