# Generated by Django 4.0.1 on 2022-01-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_fan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
